export const colors = {
    foodSecondColor: "#0000ff",
    foodMainOneColor: "#00ff00",
    foodMainFiveColor: "#ffff00",
    foodMainTenColor: "#ff0000",
    gameFieldColor: "#ffffff",
    mainTextColor: "#ffffff",
    scoreListBcgColor: "#000000",
    scoreListTextColor: "#ff0000",
    scoreListCurrentUserBcgColor: "#00b500",
    scoreListCurrentUserTxtColor: "#ffffff",
    userScoreColor: "#ffffff",
    buttonsColor: "#000000",
    snakeColor: "#705e84",
    alertMessageColor: "#ed6f95",
    loadingMessageColor: "#00ff00",
};
